### ISSUE TITLE
npm command misspelled

### ISSUE THREAD

**Issue by TibbersV** [neerugupta/flarum-lang-arabic#1]
Hello there, 

I wanted to let you know that the npm command you have in your readme is misspelled
Current command : 
`composer require yourname/flarum-lang-arabic`

How it should be : 
`composer require neerugupta/flarum-lang-arabic`

It's also incorrect in [Extiverse](https://extiverse.com/extension/neerugupta/flarum-lang-arabic)

**Comment by rob006** [comment]
It should be correct now.
